version: 2
updates:
  # Keep Composer dependencies updated
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"

  # Keep GitHub Actions updated
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
