services:
  web:
    image: bkoltz/project_alpha:latest
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html:cached
      - ./src:/var/www/src:cached
    env_file:
      - ./environment.env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8
    restart: unless-stopped

    # Define root password + user + database explicitly
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: project_alpha
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword

    volumes:
      - db_data:/var/lib/mysql
      - ./database/migrations:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: ["CMD", "mysqladmin", "--skip-ssl", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 10
volumes:
  db_data: