<?php
$queue = $pdo->query("SELECT t.*,p.name project_name,COALESCE(NULLIF(CONCAT(ep.first_name,' ',ep.last_name),' '),u.username,u.email) employee_name FROM work_time_entries t JOIN users u ON u.id=t.user_id JOIN employee_profiles ep ON ep.user_id=t.user_id LEFT JOIN projects p ON p.id=t.project_id WHERE t.status='review' ORDER BY t.start_time")->fetchAll(PDO::FETCH_ASSOC);
$approved = $pdo->query("SELECT t.*,p.name project_name,s.id snapshot_id,COALESCE(NULLIF(CONCAT(ep.first_name,' ',ep.last_name),' '),u.username,u.email) employee_name FROM work_time_entries t JOIN users u ON u.id=t.user_id JOIN employee_profiles ep ON ep.user_id=t.user_id LEFT JOIN projects p ON p.id=t.project_id LEFT JOIN work_approval_snapshots s ON s.time_entry_id=t.id AND s.entry_revision=t.revision WHERE t.status='approved' ORDER BY t.reviewed_at DESC LIMIT 50")->fetchAll(PDO::FETCH_ASSOC);
$projects = $pdo->query("SELECT id,name FROM projects WHERE status NOT IN ('completed','cancelled') ORDER BY name")->fetchAll(PDO::FETCH_ASSOC);
$h = static fn($value): string => htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
$timezone=(string)($pdo->query('SELECT timezone FROM business_settings WHERE singleton=1')->fetchColumn()?:'UTC');
$localInput=static fn(string $value):string=>(new DateTimeImmutable($value,new DateTimeZone('UTC')))->setTimezone(new DateTimeZone($timezone))->format('Y-m-d\TH:i');
?>
<div class="page-header"><div><p class="eyebrow">Workforce</p><h1>Approvals</h1><p>Review employee time and create immutable pay and billing snapshots.</p></div></div>
<?php if (!empty($_GET['success'])): ?><div class="al-alert"><?= $h($_GET['success']) ?></div><?php endif; ?><?php if (!empty($_GET['error'])): ?><div class="al-alert error"><?= $h($_GET['error']) ?></div><?php endif; ?>
<section class="al-card"><h2>Review queue</h2><?php foreach ($queue as $entry): ?><article style="border-bottom:1px solid #e2e8f0;padding:16px 0"><h3 style="margin:0 0 6px"><?= $h($entry['employee_name']) ?> · <?= $h($entry['project_name'] ?: 'No project') ?></h3><p><?= $h($entry['start_time']) ?> – <?= $h($entry['end_time']) ?> · <?= number_format(((int)$entry['duration_seconds'])/3600,2) ?> h<br><?= $h($entry['description']) ?></p><?php if ($entry['rejection_reason']): ?><p class="al-alert error"><?= $h($entry['rejection_reason']) ?></p><?php endif; ?><div class="al-actions"><form method="post" action="/approvals/action"><input type="hidden" name="csrf" value="<?= $h(csrf_token()) ?>"><input type="hidden" name="action" value="approve"><input type="hidden" name="entry_id" value="<?= $h($entry['id']) ?>"><button class="btn btn-primary">Approve</button></form><form method="post" action="/approvals/action" style="display:flex;gap:8px"><input type="hidden" name="csrf" value="<?= $h(csrf_token()) ?>"><input type="hidden" name="action" value="reject"><input type="hidden" name="entry_id" value="<?= $h($entry['id']) ?>"><input name="reason" placeholder="Rejection reason" required><button class="btn">Reject</button></form></div></article><?php endforeach; ?><?php if (!$queue): ?><p>No entries are waiting for review.</p><?php endif; ?></section>
<section class="al-card"><h2>Recently approved</h2><?php foreach ($approved as $entry): ?><details style="border-bottom:1px solid #e2e8f0;padding:12px 0"><summary><strong><?= $h($entry['employee_name']) ?></strong> · <?= $h($entry['project_name'] ?: 'No project') ?> · <?= number_format(((int)$entry['duration_seconds'])/3600,2) ?> h</summary><div style="padding:12px"><form class="al-form" method="post" action="/approvals/action"><input type="hidden" name="csrf" value="<?= $h(csrf_token()) ?>"><input type="hidden" name="action" value="correct"><input type="hidden" name="entry_id" value="<?= $h($entry['id']) ?>"><label>Project<select name="project_id"><option value="">No project</option><?php foreach ($projects as $project): ?><option value="<?= (int)$project['id'] ?>" <?= (int)$entry['project_id']===(int)$project['id']?'selected':'' ?>><?= $h($project['name']) ?></option><?php endforeach; ?></select></label><label>Start<input type="datetime-local" name="start_time" value="<?= $h($localInput($entry['start_time'])) ?>" required></label><label>End<input type="datetime-local" name="end_time" value="<?= $h($localInput($entry['end_time'])) ?>" required></label><label>Description<textarea name="description"><?= $h($entry['description']) ?></textarea></label><label><span><input style="width:auto" type="checkbox" name="billable" value="1" <?= $entry['billable']?'checked':'' ?>> Billable</span></label><label><span><input style="width:auto" type="checkbox" name="is_payable" value="1" <?= $entry['is_payable']?'checked':'' ?>> Payable</span></label><label>Correction reason<input name="reason" required></label><button class="btn">Create correction revision</button></form><form method="post" action="/approvals/action" style="display:flex;gap:8px;margin-top:12px"><input type="hidden" name="csrf" value="<?= $h(csrf_token()) ?>"><input type="hidden" name="action" value="void"><input type="hidden" name="entry_id" value="<?= $h($entry['id']) ?>"><input name="reason" placeholder="Void reason" required><button class="btn btn-danger">Void entry</button></form></div></details><?php endforeach; ?><?php if (!$approved): ?><p>No approved entries yet.</p><?php endif; ?></section>
