<?php
$h=static fn($value)=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');
$defaultUnitId=(int)($pdo->query('SELECT config_value FROM app_config WHERE organization_id=0 AND config_key="default_business_unit_id" LIMIT 1')->fetchColumn()?:0);
$units=$pdo->query('SELECT bu.*,(SELECT COUNT(*) FROM worker_business_units wbu WHERE wbu.business_unit_id=bu.id AND (wbu.ends_at IS NULL OR wbu.ends_at>UTC_TIMESTAMP(6))) worker_count,(SELECT COUNT(*) FROM client_business_units cbu WHERE cbu.business_unit_id=bu.id) client_count,(SELECT COUNT(*) FROM projects p WHERE p.business_unit_id=bu.id) project_count FROM business_units bu ORDER BY bu.is_active DESC,bu.name')->fetchAll(PDO::FETCH_ASSOC);
$selectedId=max(0,(int)($_GET['unit_id']??0));$selected=null;$unitWorkers=[];$unitClients=[];$unitProjects=[];
foreach($units as $unit)if((int)$unit['id']===$selectedId)$selected=$unit;
if($selected){$stmt=$pdo->prepare('SELECT wp.display_name FROM worker_business_units wbu JOIN worker_profiles wp ON wp.id=wbu.worker_profile_id WHERE wbu.business_unit_id=? AND (wbu.ends_at IS NULL OR wbu.ends_at>UTC_TIMESTAMP(6)) ORDER BY wp.display_name');$stmt->execute([$selectedId]);$unitWorkers=$stmt->fetchAll(PDO::FETCH_COLUMN);$stmt=$pdo->prepare('SELECT c.name FROM client_business_units cbu JOIN clients c ON c.id=cbu.client_id WHERE cbu.business_unit_id=? ORDER BY c.name');$stmt->execute([$selectedId]);$unitClients=$stmt->fetchAll(PDO::FETCH_COLUMN);$stmt=$pdo->prepare('SELECT p.name FROM projects p WHERE p.business_unit_id=? ORDER BY p.name');$stmt->execute([$selectedId]);$unitProjects=$stmt->fetchAll(PDO::FETCH_COLUMN);}
?>
<div class="settings-alert settings-alert-info">Business Units model your company structure: a branch, geographic division, department, region, or crew. Projects inherit their Unit into Operations and Tasks.</div>
<form method="post" action="/?page=settings/workforce-catalog-handler" class="settings-card">
 <input type="hidden" name="csrf" value="<?=$h(csrf_token())?>"><input type="hidden" name="action" value="save-business-unit"><input type="hidden" name="return_tab" value="business-units-divisions"><input type="hidden" name="id" value="<?=(int)($selected['id']??0)?>">
 <h3><?=$selected?'Edit Business Unit':'Add Business Unit'?></h3><p>Examples include Green Bay, Chippewa Falls, Residential Construction, or Setup Crew.</p>
 <div class="settings-form-grid"><label class="field"><span class="label">Name</span><input class="input" name="name" required value="<?=$h($selected['name']??'')?>"></label><label class="field"><span class="label">Code</span><input class="input" name="code" required value="<?=$h($selected['code']??'')?>"></label><label class="field" style="grid-column:1/-1"><span class="label">Description</span><textarea class="input" name="description" rows="2"><?=$h($selected['description']??'')?></textarea></label><label class="check-row"><input type="checkbox" name="is_active" value="1" <?=!$selected||!empty($selected['is_active'])?'checked':''?>> Active</label><label class="check-row"><input type="checkbox" name="is_default" value="1" <?=$selected&&(int)$selected['id']===$defaultUnitId?'checked':''?>> Default for new Projects</label></div>
 <button class="btn btn-primary"><?=$selected?'Save Unit':'Add Unit'?></button><?php if($selected):?> <a class="btn" href="/?page=settings&amp;tab=business-units-divisions">Cancel</a><?php endif;?>
</form>
<div class="settings-card"><h3>Business Units &amp; Divisions</h3><div class="pa-table-wrap"><table class="pa-table"><thead><tr><th>Unit</th><th>Workers</th><th>Clients</th><th>Projects</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($units as $unit):?><tr><td><strong><?=$h($unit['name'])?></strong><small><?=$h($unit['code'])?><?=(int)$unit['id']===$defaultUnitId?' · Default':''?></small></td><td><?=(int)$unit['worker_count']?></td><td><?=(int)$unit['client_count']?></td><td><?=(int)$unit['project_count']?></td><td><?=$unit['is_active']?'Active':'Inactive'?></td><td class="text-right"><a class="btn btn-sm" href="/?page=settings&amp;tab=business-units-divisions&amp;unit_id=<?=(int)$unit['id']?>">Details / edit</a></td></tr><?php endforeach;?><?php if(!$units):?><tr><td colspan="6">No Business Units yet. New Projects may remain visibly unassigned.</td></tr><?php endif;?></tbody></table></div></div>
<?php if($selected):?>
<div class="settings-card"><h3><?=$h($selected['name'])?> details</h3><div class="settings-form-grid"><div><span class="label">Workers (<?=(int)$selected['worker_count']?>)</span><p><?=$unitWorkers?$h(implode(', ',$unitWorkers)):'None assigned'?></p></div><div><span class="label">Clients (<?=(int)$selected['client_count']?>)</span><p><?=$unitClients?$h(implode(', ',$unitClients)):'None assigned'?></p></div><div><span class="label">Projects (<?=(int)$selected['project_count']?>)</span><p><?=$unitProjects?$h(implode(', ',$unitProjects)):'None assigned'?></p></div></div><p>Worker membership and scoped permissions remain under Account &amp; Access. Assign this unit to Projects from each Project’s settings.</p></div>
<?php endif;?>
