CREATE TABLE IF NOT EXISTS financial_assets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    organization_id INT NOT NULL,
    vendor_id INT NULL DEFAULT NULL,
    category_id INT NULL DEFAULT NULL,
    expense_id INT NULL DEFAULT NULL,
    asset_tag VARCHAR(80) NULL DEFAULT NULL,
    name VARCHAR(190) NOT NULL,
    asset_type VARCHAR(100) NULL DEFAULT NULL,
    serial_number VARCHAR(190) NULL DEFAULT NULL,
    status ENUM('planned','active','maintenance','retired','sold','lost','disposed') NOT NULL DEFAULT 'active',
    location VARCHAR(190) NULL DEFAULT NULL,
    purchase_date DATE NULL DEFAULT NULL,
    purchase_cost DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    depreciation_method ENUM('none','straight_line') NOT NULL DEFAULT 'straight_line',
    depreciation_start_date DATE NULL DEFAULT NULL,
    useful_life_months INT NULL DEFAULT NULL,
    salvage_value DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    warranty_expires_on DATE NULL DEFAULT NULL,
    disposed_on DATE NULL DEFAULT NULL,
    disposal_value DECIMAL(12,2) NULL DEFAULT NULL,
    notes TEXT NULL,
    created_by INT NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_fin_asset_org_tag (organization_id, asset_tag),
    INDEX idx_fin_asset_org (organization_id),
    INDEX idx_fin_asset_vendor (vendor_id),
    INDEX idx_fin_asset_category (category_id),
    INDEX idx_fin_asset_expense (expense_id),
    INDEX idx_fin_asset_status (status),
    INDEX idx_fin_asset_purchase_date (purchase_date),
    CONSTRAINT fk_fin_asset_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_fin_asset_vendor FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON DELETE SET NULL,
    CONSTRAINT fk_fin_asset_category FOREIGN KEY (category_id) REFERENCES expense_categories(id) ON DELETE SET NULL,
    CONSTRAINT fk_fin_asset_expense FOREIGN KEY (expense_id) REFERENCES expenses(id) ON DELETE SET NULL,
    CONSTRAINT fk_fin_asset_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
