-- Migration 0067: default-off signed portal projection delivery and durable dispatch state.
-- Credentials remain encrypted with APP_ENCRYPTION_KEY and destinations are operator-owned.

SET @portal_delivery_sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='portal_integration_profiles' AND column_name='delivery_enabled')=0,'ALTER TABLE portal_integration_profiles ADD COLUMN delivery_enabled TINYINT(1) NOT NULL DEFAULT 0 AFTER draft_quote_enabled','SELECT 1');PREPARE portal_delivery_stmt FROM @portal_delivery_sql;EXECUTE portal_delivery_stmt;DEALLOCATE PREPARE portal_delivery_stmt;
SET @portal_delivery_sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='portal_integration_profiles' AND column_name='delivery_key_id')=0,'ALTER TABLE portal_integration_profiles ADD COLUMN delivery_key_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL AFTER delivery_enabled','SELECT 1');PREPARE portal_delivery_stmt FROM @portal_delivery_sql;EXECUTE portal_delivery_stmt;DEALLOCATE PREPARE portal_delivery_stmt;
SET @portal_delivery_sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='portal_integration_profiles' AND column_name='delivery_previous_key_id')=0,'ALTER TABLE portal_integration_profiles ADD COLUMN delivery_previous_key_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL AFTER delivery_key_id','SELECT 1');PREPARE portal_delivery_stmt FROM @portal_delivery_sql;EXECUTE portal_delivery_stmt;DEALLOCATE PREPARE portal_delivery_stmt;
SET @portal_delivery_sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='portal_integration_profiles' AND column_name='delivery_previous_valid_until')=0,'ALTER TABLE portal_integration_profiles ADD COLUMN delivery_previous_valid_until DATETIME(6) NULL AFTER delivery_previous_key_id','SELECT 1');PREPARE portal_delivery_stmt FROM @portal_delivery_sql;EXECUTE portal_delivery_stmt;DEALLOCATE PREPARE portal_delivery_stmt;
SET @portal_delivery_sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='portal_integration_profiles' AND column_name='delivery_credentials_enc')=0,'ALTER TABLE portal_integration_profiles ADD COLUMN delivery_credentials_enc MEDIUMTEXT NULL AFTER delivery_previous_valid_until','SELECT 1');PREPARE portal_delivery_stmt FROM @portal_delivery_sql;EXECUTE portal_delivery_stmt;DEALLOCATE PREPARE portal_delivery_stmt;
SET @portal_delivery_sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='portal_integration_profiles' AND column_name='delivery_timeout_seconds')=0,'ALTER TABLE portal_integration_profiles ADD COLUMN delivery_timeout_seconds SMALLINT UNSIGNED NOT NULL DEFAULT 15 AFTER delivery_credentials_enc','SELECT 1');PREPARE portal_delivery_stmt FROM @portal_delivery_sql;EXECUTE portal_delivery_stmt;DEALLOCATE PREPARE portal_delivery_stmt;
SET @portal_delivery_sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='portal_integration_profiles' AND column_name='delivery_max_attempts')=0,'ALTER TABLE portal_integration_profiles ADD COLUMN delivery_max_attempts SMALLINT UNSIGNED NOT NULL DEFAULT 12 AFTER delivery_timeout_seconds','SELECT 1');PREPARE portal_delivery_stmt FROM @portal_delivery_sql;EXECUTE portal_delivery_stmt;DEALLOCATE PREPARE portal_delivery_stmt;

SET @portal_delivery_sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='portal_projection_outbox' AND column_name='destination_url')=0,'ALTER TABLE portal_projection_outbox ADD COLUMN destination_url VARCHAR(500) NULL AFTER route_type','SELECT 1');PREPARE portal_delivery_stmt FROM @portal_delivery_sql;EXECUTE portal_delivery_stmt;DEALLOCATE PREPARE portal_delivery_stmt;
SET @portal_delivery_sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='portal_projection_outbox' AND column_name='is_revocation')=0,'ALTER TABLE portal_projection_outbox ADD COLUMN is_revocation TINYINT(1) NOT NULL DEFAULT 0 AFTER route_type','SELECT 1');PREPARE portal_delivery_stmt FROM @portal_delivery_sql;EXECUTE portal_delivery_stmt;DEALLOCATE PREPARE portal_delivery_stmt;
SET @portal_delivery_sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='portal_projection_outbox' AND column_name='signing_key_id')=0,'ALTER TABLE portal_projection_outbox ADD COLUMN signing_key_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL AFTER destination_url','SELECT 1');PREPARE portal_delivery_stmt FROM @portal_delivery_sql;EXECUTE portal_delivery_stmt;DEALLOCATE PREPARE portal_delivery_stmt;
SET @portal_delivery_sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='portal_projection_outbox' AND column_name='claim_token')=0,'ALTER TABLE portal_projection_outbox ADD COLUMN claim_token CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL AFTER next_attempt_at','SELECT 1');PREPARE portal_delivery_stmt FROM @portal_delivery_sql;EXECUTE portal_delivery_stmt;DEALLOCATE PREPARE portal_delivery_stmt;
SET @portal_delivery_sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='portal_projection_outbox' AND column_name='claimed_at')=0,'ALTER TABLE portal_projection_outbox ADD COLUMN claimed_at DATETIME(6) NULL AFTER claim_token','SELECT 1');PREPARE portal_delivery_stmt FROM @portal_delivery_sql;EXECUTE portal_delivery_stmt;DEALLOCATE PREPARE portal_delivery_stmt;
SET @portal_delivery_sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='portal_projection_outbox' AND column_name='dead_lettered_at')=0,'ALTER TABLE portal_projection_outbox ADD COLUMN dead_lettered_at DATETIME(6) NULL AFTER delivered_at','SELECT 1');PREPARE portal_delivery_stmt FROM @portal_delivery_sql;EXECUTE portal_delivery_stmt;DEALLOCATE PREPARE portal_delivery_stmt;
SET @portal_delivery_sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='portal_projection_outbox' AND column_name='last_http_status')=0,'ALTER TABLE portal_projection_outbox ADD COLUMN last_http_status SMALLINT UNSIGNED NULL AFTER dead_lettered_at','SELECT 1');PREPARE portal_delivery_stmt FROM @portal_delivery_sql;EXECUTE portal_delivery_stmt;DEALLOCATE PREPARE portal_delivery_stmt;
SET @portal_delivery_sql=IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='portal_projection_outbox' AND index_name='idx_portal_projection_dispatch')=0,'ALTER TABLE portal_projection_outbox ADD INDEX idx_portal_projection_dispatch (delivered_at,dead_lettered_at,next_attempt_at,claimed_at,id)','SELECT 1');PREPARE portal_delivery_stmt FROM @portal_delivery_sql;EXECUTE portal_delivery_stmt;DEALLOCATE PREPARE portal_delivery_stmt;
SET @portal_delivery_sql=IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='portal_projection_outbox' AND index_name='idx_portal_projection_control')=0,'ALTER TABLE portal_projection_outbox ADD INDEX idx_portal_projection_control (integration_profile_id,is_revocation,delivered_at,dead_lettered_at,claimed_at,id)','SELECT 1');PREPARE portal_delivery_stmt FROM @portal_delivery_sql;EXECUTE portal_delivery_stmt;DEALLOCATE PREPARE portal_delivery_stmt;

UPDATE portal_projection_outbox o JOIN portal_integration_profiles p ON p.id=o.integration_profile_id
SET o.destination_url=CASE o.route_type WHEN 'portal' THEN p.portal_route ELSE p.catalog_route END,
    o.signing_key_id=p.delivery_key_id
WHERE o.destination_url IS NULL;

INSERT INTO app_config (organization_id,config_key,config_value) VALUES
    (0,'portal_outbound_delivery_enabled','0'),
    (0,'portal_authoritative_hooks_enabled','0')
ON DUPLICATE KEY UPDATE config_value=config_value;
