-- Long-term contracts (future use)
CREATE TABLE IF NOT EXISTS long_term_contracts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  base_contract_id INT NULL,
  client_id INT NOT NULL,
  doc_number INT NULL,
  project_code VARCHAR(64) NULL,
  status ENUM('draft','active','paused','cancelled','completed') NOT NULL DEFAULT 'draft',
  start_date DATE NOT NULL,
  end_date DATE NULL,
  auto_renew TINYINT(1) NOT NULL DEFAULT 0,
  renewal_term_months INT NULL,
  notice_period_days INT NULL,
  discount_type ENUM('none','percent','fixed') NOT NULL DEFAULT 'none',
  discount_value DECIMAL(10,2) NOT NULL DEFAULT 0,
  tax_percent DECIMAL(5,2) NOT NULL DEFAULT 0,
  subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
  total DECIMAL(12,2) NOT NULL DEFAULT 0,
  signed_pdf_path VARCHAR(255) NULL,
  terms TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_ltc_client (client_id),
  INDEX idx_ltc_status (status),
  INDEX idx_ltc_doc (doc_number),
  INDEX idx_ltc_project (project_code),
  CONSTRAINT fk_ltc_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  CONSTRAINT fk_ltc_base_contract FOREIGN KEY (base_contract_id) REFERENCES contracts(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Recurring invoices (future use)
CREATE TABLE IF NOT EXISTS recurring_invoices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  client_id INT NOT NULL,
  template_invoice_id INT NULL,
  project_code VARCHAR(64) NULL,
  status ENUM('active','paused','cancelled') NOT NULL DEFAULT 'active',
  interval_unit ENUM('day','week','month','year') NOT NULL DEFAULT 'month',
  interval_count INT NOT NULL DEFAULT 1,
  start_date DATE NOT NULL,
  end_date DATE NULL,
  next_run_date DATE NULL,
  last_run_date DATE NULL,
  max_occurrences INT NULL,
  occurrences_generated INT NOT NULL DEFAULT 0,
  proration TINYINT(1) NOT NULL DEFAULT 0,
  anchor_day TINYINT NULL,
  discount_type ENUM('none','percent','fixed') NOT NULL DEFAULT 'none',
  discount_value DECIMAL(10,2) NOT NULL DEFAULT 0,
  tax_percent DECIMAL(5,2) NOT NULL DEFAULT 0,
  subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
  total DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_recinv_client (client_id),
  INDEX idx_recinv_status (status),
  INDEX idx_recinv_next (next_run_date),
  INDEX idx_recinv_project (project_code),
  CONSTRAINT fk_recinv_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  CONSTRAINT fk_recinv_template FOREIGN KEY (template_invoice_id) REFERENCES invoices(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;