-- database/migrations/018_expenses.sql
-- Unified expense tracking table

CREATE TABLE IF NOT EXISTS expenses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    organization_id INT NOT NULL,
    vendor_id INT NULL DEFAULT NULL,
    category_id INT NULL DEFAULT NULL,
    client_id INT NULL DEFAULT NULL,
    project_id INT NULL DEFAULT NULL,
    receipt_id INT NULL DEFAULT NULL,
    amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    tax_amount DECIMAL(12,2) NULL DEFAULT NULL,
    total_amount DECIMAL(12,2) NULL DEFAULT NULL,
    expense_date DATE NOT NULL,
    description TEXT NULL,
    payment_method ENUM('cash','check','card','bank_transfer','paypal','venmo','other') NULL DEFAULT NULL,
    reference_number VARCHAR(255) NULL DEFAULT NULL,
    is_billable TINYINT(1) NOT NULL DEFAULT 0,
    is_tax_deductible TINYINT(1) NOT NULL DEFAULT 1,
    is_reimbursed TINYINT(1) NOT NULL DEFAULT 0,
    is_reconciled TINYINT(1) NOT NULL DEFAULT 0,
    status ENUM('pending','confirmed','reimbursed','void') NOT NULL DEFAULT 'confirmed',
    notes TEXT NULL,
    created_by INT NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_exp_org (organization_id),
    INDEX idx_exp_vendor (vendor_id),
    INDEX idx_exp_category (category_id),
    INDEX idx_exp_client (client_id),
    INDEX idx_exp_project (project_id),
    INDEX idx_exp_date (expense_date),
    INDEX idx_exp_status (status),
    INDEX idx_exp_billable (is_billable),
    CONSTRAINT fk_exp_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_exp_vendor FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON DELETE SET NULL,
    CONSTRAINT fk_exp_category FOREIGN KEY (category_id) REFERENCES expense_categories(id) ON DELETE SET NULL,
    CONSTRAINT fk_exp_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL,
    CONSTRAINT fk_exp_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL,
    CONSTRAINT fk_exp_receipt FOREIGN KEY (receipt_id) REFERENCES receipts(id) ON DELETE SET NULL,
    CONSTRAINT fk_exp_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;