-- Rollback for 025_acl_round3_fixes.sql
--
-- The backfills performed by this migration (user_organizations.role_id,
-- quotes/contracts/invoices/clients/projects.created_by,
-- quotes/invoices.organization_id) are not safely auto-reversible. Reverting
-- those columns would destroy assignment history and is intentionally left as
-- a manual, data-aware operation if ever required.
--
-- The void permission keys added by this migration can be removed with:
--   DELETE FROM role_permissions WHERE permission IN ('contracts.void','invoices.void');
