<?php

require_once __DIR__ . '/../../../config/db.php';
require_once __DIR__ . '/../../../utils/alphaledger_ledger.php';
require_once __DIR__ . '/../../../utils/audit.php';

if (($_SESSION['user']['role'] ?? '') !== 'admin') {
    http_response_code(403);
    echo '<div class="alert alert-danger">AlphaLedger Ledger is restricted to PA administrators.</div>';
    return;
}
if (!pa_al_ledger_has_history($pdo) && !pa_al_policy_enabled($pdo)) {
    http_response_code(404);
    echo '<div class="alert alert-info">AlphaLedger has not been connected.</div>';
    return;
}

$installation = $pdo->query('SELECT * FROM alphaledger_installations ORDER BY id DESC LIMIT 1')->fetch(PDO::FETCH_ASSOC) ?: null;
$policyEnabled = pa_al_policy_enabled($pdo);
$connected = $policyEnabled && $installation && in_array($installation['status'], ['active','degraded'], true);
$state = $connected ? (string)$installation['status'] : 'disconnected';
$lastSync = $installation['last_ledger_sync_at'] ?? $installation['last_success_at'] ?? null;
$tab = in_array($_GET['tab'] ?? '', ['overview','time','pay','people'], true) ? (string)$_GET['tab'] : 'overview';
$pageNo = max(1, min(10000, (int)($_GET['page_no'] ?? 1)));
$perPage = 50;
$offset = ($pageNo - 1) * $perPage;
$dateFrom = preg_match('/^\d{4}-\d{2}-\d{2}$/', (string)($_GET['date_from'] ?? '')) ? (string)$_GET['date_from'] : '';
$dateTo = preg_match('/^\d{4}-\d{2}-\d{2}$/', (string)($_GET['date_to'] ?? '')) ? (string)$_GET['date_to'] : '';
$employee = preg_match('/^[0-9a-f-]{36}$/i', (string)($_GET['employee'] ?? '')) ? strtolower((string)$_GET['employee']) : '';
$project = preg_match('/^[0-9a-f-]{36}$/i', (string)($_GET['project'] ?? '')) ? strtolower((string)$_GET['project']) : '';
$status = in_array($_GET['status'] ?? '', ['running','review','approved','rejected','voided','pending','paid'], true) ? (string)$_GET['status'] : '';

$stats = ['active_timers'=>0,'review'=>0,'approved'=>0,'people'=>0,'projects'=>0];
try {
    $stats['active_timers']=(int)$pdo->query("SELECT COUNT(*) FROM alphaledger_ledger_time_entries WHERE deleted_at IS NULL AND status='running'")->fetchColumn();
    $stats['review']=(int)$pdo->query("SELECT COUNT(*) FROM alphaledger_ledger_time_entries WHERE deleted_at IS NULL AND status='review'")->fetchColumn();
    $stats['approved']=(int)$pdo->query("SELECT COUNT(*) FROM alphaledger_ledger_time_entries WHERE deleted_at IS NULL AND status='approved'")->fetchColumn();
    $stats['people']=(int)$pdo->query("SELECT COUNT(*) FROM alphaledger_ledger_people WHERE deleted_at IS NULL AND is_active=1")->fetchColumn();
    $stats['projects']=(int)$pdo->query("SELECT COUNT(*) FROM alphaledger_ledger_projects WHERE deleted_at IS NULL AND is_archived=0")->fetchColumn();
} catch (Throwable $ignored) {}
$payTotals=$pdo->query("SELECT currency,SUM(CASE WHEN deleted_at IS NULL AND status<>'voided' THEN amount ELSE 0 END) total,SUM(CASE WHEN deleted_at IS NULL AND status='pending' THEN amount ELSE 0 END) pending,SUM(CASE WHEN deleted_at IS NULL AND status='paid' THEN amount ELSE 0 END) paid FROM employee_pay_records GROUP BY currency ORDER BY currency")->fetchAll(PDO::FETCH_ASSOC);
$peopleOptions=$pdo->query("SELECT external_id,display_name FROM alphaledger_ledger_people WHERE deleted_at IS NULL ORDER BY display_name LIMIT 500")->fetchAll(PDO::FETCH_ASSOC);
$projectOptions=$pdo->query("SELECT external_id,name FROM alphaledger_ledger_projects WHERE deleted_at IS NULL ORDER BY name LIMIT 500")->fetchAll(PDO::FETCH_ASSOC);

$timeRows=[]; $payRows=[]; $peopleRows=[]; $projectRows=[]; $assignmentRows=[]; $detail=null; $breakRows=[]; $revisionRows=[]; $hasNext=false;
if ($tab === 'time') {
    $where=['t.deleted_at IS NULL']; $params=[];
    if($dateFrom!==''){$where[]='t.start_time>=?';$params[]=$dateFrom.' 00:00:00';}
    if($dateTo!==''){$where[]='t.start_time<=?';$params[]=$dateTo.' 23:59:59';}
    if($employee!==''){$where[]='t.employee_external_id=?';$params[]=$employee;}
    if($project!==''){$where[]='t.project_external_id=?';$params[]=$project;}
    if(in_array($status,['running','review','approved','rejected','voided'],true)){$where[]='t.status=?';$params[]=$status;}
    $sql='SELECT t.*,p.display_name employee_name,j.name project_name FROM alphaledger_ledger_time_entries t LEFT JOIN alphaledger_ledger_people p ON p.installation_id=t.installation_id AND p.external_id=t.employee_external_id LEFT JOIN alphaledger_ledger_projects j ON j.installation_id=t.installation_id AND j.external_id=t.project_external_id WHERE '.implode(' AND ',$where).' ORDER BY t.start_time DESC LIMIT '.($perPage+1).' OFFSET '.$offset;
    $stmt=$pdo->prepare($sql);$stmt->execute($params);$timeRows=$stmt->fetchAll(PDO::FETCH_ASSOC);$hasNext=count($timeRows)>$perPage;if($hasNext)array_pop($timeRows);
    $entryId=(string)($_GET['entry']??'');
    if(preg_match('/^[0-9a-f-]{36}$/i',$entryId)){
        $stmt=$pdo->prepare('SELECT t.*,p.display_name employee_name,j.name project_name FROM alphaledger_ledger_time_entries t LEFT JOIN alphaledger_ledger_people p ON p.installation_id=t.installation_id AND p.external_id=t.employee_external_id LEFT JOIN alphaledger_ledger_projects j ON j.installation_id=t.installation_id AND j.external_id=t.project_external_id WHERE t.external_id=? LIMIT 1');$stmt->execute([$entryId]);$detail=$stmt->fetch(PDO::FETCH_ASSOC)?:null;
        if($detail){$stmt=$pdo->prepare('SELECT * FROM alphaledger_ledger_breaks WHERE installation_id=? AND time_entry_external_id=? AND deleted_at IS NULL ORDER BY start_time');$stmt->execute([(int)$detail['installation_id'],$entryId]);$breakRows=$stmt->fetchAll(PDO::FETCH_ASSOC);$stmt=$pdo->prepare('SELECT r.*,p.display_name created_by_name FROM alphaledger_ledger_revisions r LEFT JOIN alphaledger_ledger_people p ON p.installation_id=r.installation_id AND p.external_id=r.created_by_external_id WHERE r.installation_id=? AND r.time_entry_external_id=? AND r.deleted_at IS NULL ORDER BY r.entry_revision DESC');$stmt->execute([(int)$detail['installation_id'],$entryId]);$revisionRows=$stmt->fetchAll(PDO::FETCH_ASSOC);}
    }
} elseif ($tab === 'pay') {
    $where=['e.deleted_at IS NULL'];$params=[];
    if($dateFrom!==''){$where[]='COALESCE(e.accrued_at,e.created_at)>=?';$params[]=$dateFrom.' 00:00:00';}if($dateTo!==''){$where[]='COALESCE(e.accrued_at,e.created_at)<=?';$params[]=$dateTo.' 23:59:59';}if($employee!==''){$where[]='e.external_employee_id=?';$params[]=$employee;}if(in_array($status,['pending','paid','voided'],true)){$where[]='e.status=?';$params[]=$status;}
    $stmt=$pdo->prepare('SELECT e.*,COALESCE(NULLIF(e.employee_name_snapshot,\'\'),p.display_name,u.username,u.email) employee_name FROM employee_pay_records e LEFT JOIN alphaledger_ledger_people p ON p.installation_id=e.installation_id AND p.external_id=e.external_employee_id LEFT JOIN users u ON u.id=e.user_id WHERE '.implode(' AND ',$where).' ORDER BY COALESCE(e.accrued_at,e.created_at) DESC LIMIT '.($perPage+1).' OFFSET '.$offset);$stmt->execute($params);$payRows=$stmt->fetchAll(PDO::FETCH_ASSOC);$hasNext=count($payRows)>$perPage;if($hasNext)array_pop($payRows);
} elseif ($tab === 'people') {
    $peopleRows=$pdo->query('SELECT * FROM alphaledger_ledger_people WHERE deleted_at IS NULL ORDER BY display_name LIMIT '.($perPage+1).' OFFSET '.$offset)->fetchAll(PDO::FETCH_ASSOC);$hasNext=count($peopleRows)>$perPage;if($hasNext)array_pop($peopleRows);
    $projectRows=$pdo->query('SELECT * FROM alphaledger_ledger_projects WHERE deleted_at IS NULL ORDER BY name LIMIT 500')->fetchAll(PDO::FETCH_ASSOC);
    $assignmentRows=$pdo->query('SELECT a.*,p.display_name employee_name,j.name project_name FROM alphaledger_ledger_assignments a LEFT JOIN alphaledger_ledger_people p ON p.installation_id=a.installation_id AND p.external_id=a.employee_external_id LEFT JOIN alphaledger_ledger_projects j ON j.installation_id=a.installation_id AND j.external_id=a.project_external_id WHERE a.deleted_at IS NULL AND a.is_active=1 ORDER BY j.name,p.display_name LIMIT 500')->fetchAll(PDO::FETCH_ASSOC);
}
audit_log($pdo,'alphaledger.ledger_viewed','alphaledger_installation',$installation?(int)$installation['id']:null,['tab'=>$tab]);

function al_ledger_duration($seconds): string { if($seconds===null)return 'Running';$seconds=(int)$seconds;return sprintf('%dh %02dm',intdiv($seconds,3600),intdiv($seconds%3600,60)); }
function al_ledger_query(array $replace=[]): string { $query=array_merge($_GET,$replace);if(!array_key_exists('entry',$replace))unset($query['entry']);return '/?'.http_build_query($query); }
?>
<style>
.al-ledger{display:grid;gap:16px}.al-ledger-head,.al-ledger-card{background:#fff;border:1px solid #dfe3e8;border-radius:12px;padding:16px}.al-ledger-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.al-ledger-state{display:inline-flex;align-items:center;gap:6px;border-radius:999px;padding:6px 10px;font-weight:700;font-size:12px;background:#f1f5f9;color:#475569}.al-ledger-state.active{background:#dcfce7;color:#166534}.al-ledger-state.degraded{background:#fef3c7;color:#92400e}.al-ledger-tabs{display:flex;gap:8px;flex-wrap:wrap}.al-ledger-tabs a{padding:8px 12px;border:1px solid #cbd5e1;border-radius:8px;text-decoration:none}.al-ledger-tabs a.active{background:var(--nav-accent);color:#fff;border-color:var(--nav-accent)}.al-ledger-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px}.al-ledger-stat{background:#fff;border:1px solid #dfe3e8;border-radius:10px;padding:14px}.al-ledger-stat strong{display:block;font-size:24px}.al-ledger-filter{display:flex;gap:10px;align-items:end;flex-wrap:wrap}.al-ledger-filter label{display:grid;gap:4px}.al-ledger-filter input,.al-ledger-filter select{padding:8px;border:1px solid #cbd5e1;border-radius:7px}.al-ledger-table{width:100%;border-collapse:collapse;font-size:13px}.al-ledger-table th,.al-ledger-table td{padding:9px;border-bottom:1px solid #e2e8f0;text-align:left;vertical-align:top}.al-ledger-table small{display:block;color:var(--muted)}.al-ledger-detail{border-left:4px solid var(--nav-accent)}@media(max-width:700px){.al-ledger-head{display:grid}.al-ledger-table{min-width:760px}}
</style>
<section class="al-ledger">
  <header class="al-ledger-head"><div><p class="finance-eyebrow">Financial workspace</p><h2 style="margin:4px 0">AlphaLedger Ledger</h2><p style="margin:0;color:var(--muted)">Read-only operational time and employee-pay data. PA accounting totals remain separate.</p></div><div><span class="al-ledger-state <?php echo htmlspecialchars($state); ?>"><?php echo htmlspecialchars(ucfirst($state)); ?></span><small style="display:block;margin-top:6px;color:var(--muted)">Last sync: <?php echo htmlspecialchars((string)($lastSync ?: 'Never')); ?></small></div></header>
  <?php if(!$connected): ?><div class="alert alert-warning"><strong>Historical data:</strong> AlphaLedger is disconnected. This Ledger is read-only and may be stale.</div><?php elseif($state==='degraded'): ?><div class="alert alert-warning">AlphaLedger delivery is degraded. Recent changes may be delayed.</div><?php endif; ?>
  <nav class="al-ledger-tabs" aria-label="Ledger sections"><a class="<?php echo $tab==='overview'?'active':''; ?>" href="/?page=financial/ledger&tab=overview">Overview</a><a class="<?php echo $tab==='time'?'active':''; ?>" href="/?page=financial/ledger&tab=time">Time Entries</a><a class="<?php echo $tab==='pay'?'active':''; ?>" href="/?page=financial/ledger&tab=pay">Employee Pay</a><a class="<?php echo $tab==='people'?'active':''; ?>" href="/?page=financial/ledger&tab=people">People &amp; Assignments</a></nav>
  <?php if($tab==='overview'): ?>
    <div class="al-ledger-grid"><div class="al-ledger-stat"><span>Active timers</span><strong><?php echo $stats['active_timers']; ?></strong></div><div class="al-ledger-stat"><span>Awaiting review</span><strong><?php echo $stats['review']; ?></strong></div><div class="al-ledger-stat"><span>Approved entries</span><strong><?php echo $stats['approved']; ?></strong></div><div class="al-ledger-stat"><span>Active people</span><strong><?php echo $stats['people']; ?></strong></div><div class="al-ledger-stat"><span>Active projects</span><strong><?php echo $stats['projects']; ?></strong></div></div>
    <div class="al-ledger-card"><h3>Employee Pay</h3><p>Employee pay is not included in Income, Expenses, or Net Profit.</p><?php if(!$payTotals): ?><p>No pay accruals.</p><?php else: ?><table class="al-ledger-table"><thead><tr><th>Currency</th><th>Accrued</th><th>Pending</th><th>Paid</th></tr></thead><tbody><?php foreach($payTotals as $row): ?><tr><td><?php echo htmlspecialchars($row['currency']); ?></td><td><?php echo htmlspecialchars(number_format((float)$row['total'],2)); ?></td><td><?php echo htmlspecialchars(number_format((float)$row['pending'],2)); ?></td><td><?php echo htmlspecialchars(number_format((float)$row['paid'],2)); ?></td></tr><?php endforeach; ?></tbody></table><?php endif; ?><p><a class="btn btn-sm" href="/?page=financial/expenses-list&tab=employee-pay">Manage payment status</a></p></div>
  <?php elseif($tab==='time'): ?>
    <form class="al-ledger-card al-ledger-filter" method="get"><input type="hidden" name="page" value="financial/ledger"><input type="hidden" name="tab" value="time"><label>From<input type="date" name="date_from" value="<?php echo htmlspecialchars($dateFrom); ?>"></label><label>To<input type="date" name="date_to" value="<?php echo htmlspecialchars($dateTo); ?>"></label><label>Employee<select name="employee"><option value="">All</option><?php foreach($peopleOptions as $o): ?><option value="<?php echo htmlspecialchars($o['external_id']); ?>" <?php echo $employee===$o['external_id']?'selected':''; ?>><?php echo htmlspecialchars($o['display_name']); ?></option><?php endforeach; ?></select></label><label>Project<select name="project"><option value="">All</option><?php foreach($projectOptions as $o): ?><option value="<?php echo htmlspecialchars($o['external_id']); ?>" <?php echo $project===$o['external_id']?'selected':''; ?>><?php echo htmlspecialchars($o['name']); ?></option><?php endforeach; ?></select></label><label>Status<select name="status"><option value="">All</option><?php foreach(['running','review','approved','rejected','voided'] as $s): ?><option <?php echo $status===$s?'selected':''; ?>><?php echo $s; ?></option><?php endforeach; ?></select></label><button class="btn btn-primary">Apply</button></form>
    <?php if($detail): ?><div class="al-ledger-card al-ledger-detail"><h3>Entry details</h3><p><strong><?php echo htmlspecialchars((string)($detail['employee_name']?:$detail['employee_external_id'])); ?></strong> · <?php echo htmlspecialchars((string)($detail['project_name']?:'No project')); ?> · <?php echo htmlspecialchars($detail['status']); ?></p><p><?php echo nl2br(htmlspecialchars((string)$detail['description'])); ?></p><?php if($detail['rejection_reason']!==''): ?><p><strong>Rejection:</strong> <?php echo htmlspecialchars($detail['rejection_reason']); ?></p><?php endif; ?><h4>Breaks</h4><?php if(!$breakRows): ?><p>None</p><?php else: ?><ul><?php foreach($breakRows as $b): ?><li><?php echo htmlspecialchars($b['start_time']); ?> – <?php echo htmlspecialchars((string)($b['end_time']?:'Running')); ?> (<?php echo htmlspecialchars(al_ledger_duration($b['duration_seconds'])); ?>)</li><?php endforeach; ?></ul><?php endif; ?><h4>Corrections and revisions</h4><?php if(!$revisionRows): ?><p>None</p><?php else: ?><ul><?php foreach($revisionRows as $r): ?><li>Revision <?php echo (int)$r['entry_revision']; ?> by <?php echo htmlspecialchars((string)($r['created_by_name']?:$r['created_by_external_id'])); ?> — <?php echo htmlspecialchars($r['reason']); ?></li><?php endforeach; ?></ul><?php endif; ?></div><?php endif; ?>
    <div class="al-ledger-card" style="overflow:auto"><table class="al-ledger-table"><thead><tr><th>Start</th><th>Employee</th><th>Project</th><th>Duration</th><th>Status</th><th>Description</th><th></th></tr></thead><tbody><?php foreach($timeRows as $r): ?><tr><td><?php echo htmlspecialchars($r['start_time']); ?></td><td><?php echo htmlspecialchars((string)($r['employee_name']?:$r['employee_external_id'])); ?></td><td><?php echo htmlspecialchars((string)($r['project_name']?:'—')); ?></td><td><?php echo htmlspecialchars(al_ledger_duration($r['duration_seconds'])); ?></td><td><?php echo htmlspecialchars($r['status']); ?></td><td><?php echo htmlspecialchars(mb_strimwidth((string)$r['description'],0,80,'…')); ?></td><td><a href="<?php echo htmlspecialchars(al_ledger_query(['entry'=>$r['external_id']])); ?>">Details</a></td></tr><?php endforeach; ?><?php if(!$timeRows): ?><tr><td colspan="7">No matching entries.</td></tr><?php endif; ?></tbody></table></div>
  <?php elseif($tab==='pay'): ?>
    <form class="al-ledger-card al-ledger-filter" method="get"><input type="hidden" name="page" value="financial/ledger"><input type="hidden" name="tab" value="pay"><label>From<input type="date" name="date_from" value="<?php echo htmlspecialchars($dateFrom); ?>"></label><label>To<input type="date" name="date_to" value="<?php echo htmlspecialchars($dateTo); ?>"></label><label>Employee<select name="employee"><option value="">All</option><?php foreach($peopleOptions as $o): ?><option value="<?php echo htmlspecialchars($o['external_id']); ?>" <?php echo $employee===$o['external_id']?'selected':''; ?>><?php echo htmlspecialchars($o['display_name']); ?></option><?php endforeach; ?></select></label><label>Status<select name="status"><option value="">All</option><?php foreach(['pending','paid','voided'] as $s): ?><option <?php echo $status===$s?'selected':''; ?>><?php echo $s; ?></option><?php endforeach; ?></select></label><button class="btn btn-primary">Apply</button></form>
    <div class="al-ledger-card" style="overflow:auto"><p><strong>Employee Pay is separate from income, expenses, and net profit.</strong></p><table class="al-ledger-table"><thead><tr><th>Accrued</th><th>Employee</th><th>Hours</th><th>Rate</th><th>Amount</th><th>Status</th></tr></thead><tbody><?php foreach($payRows as $r): ?><tr><td><?php echo htmlspecialchars((string)($r['accrued_at']?:$r['created_at'])); ?></td><td><?php echo htmlspecialchars((string)($r['employee_name']?:$r['external_employee_id'])); ?></td><td><?php echo htmlspecialchars($r['hours']); ?></td><td><?php echo htmlspecialchars($r['currency'].' '.number_format((float)$r['rate'],4)); ?></td><td><?php echo htmlspecialchars($r['currency'].' '.number_format((float)$r['amount'],2)); ?></td><td><?php echo htmlspecialchars($r['status']); ?></td></tr><?php endforeach; ?><?php if(!$payRows): ?><tr><td colspan="6">No matching pay records.</td></tr><?php endif; ?></tbody></table><p><a class="btn btn-sm" href="/?page=financial/expenses-list&tab=employee-pay">Manage payment status</a></p></div>
  <?php else: ?>
    <div class="al-ledger-card" style="overflow:auto"><h3>People</h3><table class="al-ledger-table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>PA link</th><th>State</th></tr></thead><tbody><?php foreach($peopleRows as $r): ?><tr><td><?php echo htmlspecialchars($r['display_name']); ?></td><td><?php echo htmlspecialchars($r['email']); ?></td><td><?php echo htmlspecialchars($r['role']); ?></td><td><?php echo htmlspecialchars((string)($r['pa_person_id']?:'Unlinked')); ?></td><td><?php echo $r['is_active']?'Active':'Inactive'; ?></td></tr><?php endforeach; ?></tbody></table></div>
    <div class="al-ledger-card" style="overflow:auto"><h3>Projects &amp; assignments</h3><table class="al-ledger-table"><thead><tr><th>Project</th><th>Origin</th><th>Assigned employee</th></tr></thead><tbody><?php foreach($assignmentRows as $r): ?><tr><td><?php echo htmlspecialchars((string)($r['project_name']?:$r['project_external_id'])); ?></td><td><?php $origin='';foreach($projectRows as $p){if($p['external_id']===$r['project_external_id']){$origin=$p['origin'];break;}}echo htmlspecialchars($origin); ?></td><td><?php echo htmlspecialchars((string)($r['employee_name']?:$r['employee_external_id'])); ?></td></tr><?php endforeach; ?><?php if(!$assignmentRows): ?><tr><td colspan="3">No active assignments.</td></tr><?php endif; ?></tbody></table></div>
  <?php endif; ?>
  <?php if($pageNo>1||$hasNext): ?><div style="display:flex;gap:8px"><?php if($pageNo>1): ?><a class="btn" href="<?php echo htmlspecialchars(al_ledger_query(['page_no'=>$pageNo-1])); ?>">Previous</a><?php endif; ?><?php if($hasNext): ?><a class="btn" href="<?php echo htmlspecialchars(al_ledger_query(['page_no'=>$pageNo+1])); ?>">Next</a><?php endif; ?></div><?php endif; ?>
</section>
