<?php
require_once __DIR__.'/../../utils/mileage.php';
$travelRule=$travelRule??[];$travelUserId=(int)($_SESSION['user']['id']??0);$travelOrgId=function_exists('request_client_org_id')?request_client_org_id():0;
if(!$travelRule&&!empty($travelRuleScope)&&!empty($travelDocumentId)){
  try{$col=$travelRuleScope==='contract'?'contract_id':'quote_id';$tr=$pdo->prepare("SELECT * FROM travel_billing_rules WHERE scope_type=? AND {$col}=? ORDER BY id DESC LIMIT 1");$tr->execute([$travelRuleScope,(int)$travelDocumentId]);$travelRule=$tr->fetch(PDO::FETCH_ASSOC)?:[];}catch(Throwable $e){$travelRule=[];}
}
$hasDocumentTravelRule=!empty($travelRule);
$travelRule+=['charge_method'=>'none','mileage_rate'=>(float)($appConfig['default_mileage_rate']??0.670),'included_miles'=>(float)($appConfig['default_mileage_included_miles']??0),'charge_return'=>!empty($appConfig['default_mileage_bill_return_trip']),'fixed_amount'=>0,'origin_id'=>null,'service_location_id'=>null,'estimated_one_way_miles'=>null,'terms_text'=>''];
try{$to=$pdo->prepare('SELECT id,label FROM user_mileage_origins WHERE user_id=? ORDER BY is_default DESC,label');$to->execute([$travelUserId]);$travelOrigins=$to->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable $e){$travelOrigins=[];}
try{$tl=$pdo->prepare('SELECT id,client_id,name,city,state FROM service_locations WHERE archived=0 AND (?=0 OR organization_id=?) ORDER BY name');$tl->execute([$travelOrgId,$travelOrgId]);$travelLocations=$tl->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable $e){$travelLocations=[];}
try{$tcr=$pdo->prepare('SELECT * FROM travel_billing_rules WHERE scope_type="client" AND (organization_id IS NULL OR organization_id=?) ORDER BY id');$tcr->execute([$travelOrgId]);$travelClientRules=$tcr->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable $e){$travelClientRules=[];}
?>
<fieldset class="card" data-travel-rule-fields data-has-document-rule="<?php echo $hasDocumentTravelRule?'1':'0'; ?>" data-client-rules="<?php echo htmlspecialchars(json_encode($travelClientRules),ENT_QUOTES,'UTF-8'); ?>" style="border:1px solid #dbeafe"><legend style="padding:0 8px;font-weight:700">Client travel pricing</legend><p class="muted">Disclose the rule now. Approved mileage or a fixed fee becomes a visible invoice line later.</p>
 <div class="grid grid-2"><label class="field"><span class="label">Travel charge method</span><select class="input" name="travel_charge_method" data-travel-method><option value="none" <?php echo $travelRule['charge_method']==='none'?'selected':''; ?>>No client travel charge</option><option value="actual_trip" <?php echo $travelRule['charge_method']==='actual_trip'?'selected':''; ?>>Approved actual trip distance</option><option value="origin_distance" <?php echo $travelRule['charge_method']==='origin_distance'?'selected':''; ?>>Billing origin to service location</option><option value="fixed_fee" <?php echo $travelRule['charge_method']==='fixed_fee'?'selected':''; ?>>Fixed travel fee</option></select></label><label class="field" data-travel-fixed><span class="label">Fixed travel fee</span><input class="input" type="number" min="0" step="0.01" name="travel_fixed_amount" value="<?php echo number_format((float)$travelRule['fixed_amount'],2,'.',''); ?>"></label></div>
 <div data-travel-mileage><div class="grid grid-2"><label class="field"><span class="label">Rate per billable mile</span><input class="input" type="number" min="0" step="0.0001" name="travel_mileage_rate" value="<?php echo number_format((float)$travelRule['mileage_rate'],4,'.',''); ?>"></label><label class="field"><span class="label">Included miles before charging</span><input class="input" type="number" min="0" step="0.001" name="travel_included_miles" value="<?php echo number_format((float)$travelRule['included_miles'],3,'.',''); ?>"></label></div><div class="grid grid-2"><label class="field"><span class="label">Optional estimated one-way miles</span><input class="input" type="number" min="0" step="0.001" name="travel_estimated_one_way_miles" value="<?php echo $travelRule['estimated_one_way_miles']!==null?number_format((float)$travelRule['estimated_one_way_miles'],3,'.',''):''; ?>"><small class="muted">Leave blank for a rate-only variable line.</small></label><label class="field"><span class="label">Directions charged</span><span style="display:flex;gap:8px;align-items:center"><input type="checkbox" name="travel_charge_return" value="1" <?php echo !empty($travelRule['charge_return'])?'checked':''; ?>> Charge return travel</span></label></div></div>
 <div class="grid grid-2" data-travel-origin><label class="field"><span class="label">Private billing origin</span><select class="input" name="travel_origin_id"><option value="">Choose origin</option><?php foreach($travelOrigins as $x): ?><option value="<?php echo (int)$x['id']; ?>" <?php echo (int)$travelRule['origin_id']===(int)$x['id']?'selected':''; ?>><?php echo htmlspecialchars($x['label']); ?></option><?php endforeach; ?></select></label><label class="field"><span class="label">Service location</span><select class="input" name="travel_service_location_id"><option value="">Choose location</option><?php foreach($travelLocations as $x): ?><option value="<?php echo (int)$x['id']; ?>" data-client-id="<?php echo (int)$x['client_id']; ?>" <?php echo (int)$travelRule['service_location_id']===(int)$x['id']?'selected':''; ?>><?php echo htmlspecialchars($x['name']); ?></option><?php endforeach; ?></select></label></div>
 <label class="field"><span class="label">Travel terms shown to the client</span><textarea class="input" rows="2" name="travel_terms_text" placeholder="Optional clarification for this quote or contract"><?php echo htmlspecialchars((string)$travelRule['terms_text']); ?></textarea></label>
</fieldset><script src="<?php echo htmlspecialchars(asset_url('/assets/js/travel-rule.js'),ENT_QUOTES,'UTF-8'); ?>" defer></script>
