name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

# ensure you keep the file header/triggers as-is
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@main
        with:
          php-version: '8.2'
          extensions: 'mbstring, mysqli, pdo_mysql'
          tools: 'composer:2'

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/composer
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader

